language: python
python:
  - "2.7"
node_js:
  - '0.10'
before_script:
  - 'gem update --system'
  - 'gem install compass'
  - 'npm install -g grunt-cli'
  - mysql -e 'create database waaave_testing;'
  - mysql -e 'grant CREATE,INSERT,DELETE,UPDATE,SELECT on waaave_testing.* to waaave@localhost identified by "";'
script: "./tools/test.py"
